UPDATE "Role"
SET "shortName" = CASE "name"
  WHEN 'ARTIST_3D' THEN '3DART'
  WHEN 'UNITY_DEVELOPER' THEN 'UNITY'
  WHEN 'BACKEND_DEVELOPER' THEN 'BACK'
  WHEN 'ANALYST' THEN 'ANLST'
  WHEN 'UX_DESIGNER' THEN 'UX'
  WHEN 'QA_ENGINEER' THEN 'QA'
  WHEN 'UI_DESIGNER' THEN 'UI'
  WHEN 'VIEWER' THEN 'VIEW'
  WHEN 'FINANCE' THEN 'FIN'
  ELSE "name"
END
WHERE "shortName" IS NULL;