export const ErrorCode = {
  AUTH_INVALID_CREDENTIALS: 'ERR_AUTH_INVALID_CREDENTIALS',
  ROLE_NOT_FOUND: 'ERR_ROLE_NOT_FOUND',
  EMPLOYEE_NOT_FOUND: 'ERR_EMPLOYEE_NOT_FOUND',
  DEPARTMENT_NOT_FOUND: 'ERR_DEPARTMENT_NOT_FOUND',
  SKILL_NOT_FOUND: 'ERR_SKILL_NOT_FOUND',
  COST_RATE_NOT_FOUND: 'ERR_COST_RATE_NOT_FOUND',
  COST_RATE_SCOPE_REQUIRED: 'ERR_COST_RATE_SCOPE_REQUIRED',
  COST_RATE_DATE_RANGE_INVALID: 'ERR_COST_RATE_DATE_RANGE_INVALID',
  VACATION_NOT_FOUND: 'ERR_VACATION_NOT_FOUND',
  PROJECT_NOT_FOUND: 'ERR_PROJECT_NOT_FOUND',
  PROJECT_CODE_ALREADY_EXISTS: 'ERR_PROJECT_CODE_ALREADY_EXISTS',
  ASSIGNMENT_NOT_FOUND: 'ERR_ASSIGNMENT_NOT_FOUND',
  PROJECT_DATE_RANGE_INVALID: 'ERR_PROJECT_DATE_RANGE_INVALID',
  VACATION_DATE_RANGE_INVALID: 'ERR_VACATION_DATE_RANGE_INVALID',
  ASSIGNMENT_DATE_RANGE_INVALID: 'ERR_ASSIGNMENT_DATE_RANGE_INVALID',
  ASSIGNMENT_OUTSIDE_PROJECT_RANGE: 'ERR_ASSIGNMENT_OUTSIDE_PROJECT_RANGE',
  ASSIGNMENT_EMPLOYEE_OVERLOADED: 'ERR_ASSIGNMENT_EMPLOYEE_OVERLOADED',
  ASSIGNMENT_OVERLAPS_VACATION: 'ERR_ASSIGNMENT_OVERLAPS_VACATION',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
