import { DEFAULT_FALLBACK_COLOR_HEX, MIN_TIMELINE_BAR_WIDTH_PERCENT, MS_PER_DAY } from '../../constants/app.constants';

export { MS_PER_DAY };
export const ASSIGNMENT_MIN_WIDTH_PERCENT = MIN_TIMELINE_BAR_WIDTH_PERCENT;
export const ASSIGNMENT_DRAG_THRESHOLD_PX = 2;
export const ASSIGNMENT_EDGE_WIDTH_PX = 8;
export const TIMELINE_FALLBACK_COLOR_HEX = DEFAULT_FALLBACK_COLOR_HEX;